services:
  simplestproject.api:
    image: ${DOCKER_REGISTRY-}simplestprojectapi
    build:
      context: .
      dockerfile: src/SimplestProject.API/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433